#!/usr/bin/env python

IP_ADDRESS = 'https://172.31.216.24'
USERNAME = 'admin'
PASSWORD = 'scotch123'

TENANT = 'THISISMYTENANT'

APP_PROFILE = 'TestApp'

MY_EPG = 'TestEPG'

CONTEXT = 'TestVRF'

BD = 'TestBD'

INTERFACE1_TYPE = 'eth'
POD1 = '10'
NODE1 = '101'
MODULE1 = '1'
PORT1 = '15'

INTERFACE2_TYPE = 'eth'
POD2 = '10'
NODE2 = '101'
MODULE2 = '1'
PORT2 = '16'

L2_INTERFACE1 = 'vlan5_on_if1'
L2_ENCAPSULATION_TECHNOLOGY1 = 'vlan'
VIRTUAL_NETWORK_IDENTIFIER1 = '5'

L2_INTERFACE2 = 'vlan5_on_if2'
L2_ENCAPSULATION_TECHNOLOGY2 = 'vlan'
VIRTUAL_NETWORK_IDENTIFIER2 = '5'
